{match, [ErtsNumber]} = re:run(erlang:system_info(otp_release), "(\\d+)", [{capture, [0], list}]),
ErtsVsn = erlang:list_to_integer(ErtsNumber),
if
    ErtsVsn < 17 ->
        OldOpts = proplists:get_value(erl_opts, CONFIG, []),
        NewOpts = [{d, have_not_parameterized_dict_and_sets_support} | OldOpts],
        lists:keystore(erl_opts, 1, CONFIG, {erl_opts, NewOpts});
    true ->
        CONFIG
end.
